spring:
  datasource:
    url: jdbc:sqlserver://verwaltungssoftwareserver.database.windows.net:1433;database=VerwaltungssoftwareDB;
    username: Admin_Verwlatungssoftware@verwaltungssoftwareserver
    password: Aschachtal123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    database: sql_server
  data:
    rest:
      default-media-type: application/json
server:
  port: 8081